# Generated by Django 3.2 on 2021-06-11 16:08

import aplikacija.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=45)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=aplikacija.models.get_defaultimg, max_length=255, null=True, upload_to=aplikacija.models.get_profile_image_filepath)),
                ('gender', models.CharField(max_length=45)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('opis', models.TextField()),
                ('slika', models.ImageField(upload_to='static/img_artikli')),
                ('slika2', models.ImageField(upload_to='static/img_artikli')),
                ('slika3', models.ImageField(upload_to='static/img_artikli')),
                ('slika4', models.ImageField(upload_to='static/img_artikli')),
                ('datum_objave', models.DateField(auto_now_add=True)),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=9)),
                ('izdvojen', models.CharField(max_length=10)),
                ('id_kategorija', models.IntegerField(null=True)),
                ('id_podkategorija', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periferija_i_memorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periferija_i_memorija', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika1', models.ImageField(upload_to='static/img_slideShow')),
                ('slika2', models.ImageField(upload_to='static/img_slideShow')),
                ('slika3', models.ImageField(upload_to='static/img_slideShow')),
            ],
        ),
    ]
