# Generated by Django 3.1.12 on 2021-06-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0004_shopcart_id_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genGuest', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='id_customer',
            field=models.IntegerField(null=True),
        ),
    ]
