# Generated by Django 3.1.12 on 2021-06-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0005_auto_20210620_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id_genGuest',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='id_customer',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
