# Generated by Django 3.1.12 on 2021-06-22 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0006_auto_20210620_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='data start'),
            preserve_default=False,
        ),
    ]
