# Generated by Django 3.1.12 on 2021-06-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0007_shopcart_date_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
