# Generated by Django 3.1.12 on 2021-06-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0008_delete_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.TimeField(auto_now_add=True, verbose_name='data start'),
        ),
    ]
