# Generated by Django 3.1.12 on 2021-06-29 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0010_auto_20210622_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklama1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika1', models.ImageField(upload_to='static/reklama1')),
                ('slika2', models.ImageField(upload_to='static/reklama1')),
                ('slika3', models.ImageField(upload_to='static/reklama1')),
            ],
        ),
        migrations.CreateModel(
            name='Reklama2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika1', models.ImageField(upload_to='static/reklama2')),
                ('slika2', models.ImageField(upload_to='static/reklama2')),
                ('slika3', models.ImageField(upload_to='static/reklama2')),
            ],
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 14, 5, 29, 712553)),
        ),
    ]
