# Generated by Django 3.1.12 on 2021-06-30 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0011_auto_20210629_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 17, 50, 37, 373555)),
        ),
    ]
