# Generated by Django 3.1.12 on 2021-07-02 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0012_auto_20210630_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 15, 48, 20, 682304)),
        ),
    ]
