# Generated by Django 3.1.12 on 2021-07-02 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0013_auto_20210702_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 17, 13, 9, 205898)),
        ),
    ]
