# Generated by Django 3.1.12 on 2021-07-02 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0014_auto_20210702_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 17, 15, 30, 273971)),
        ),
    ]
