# Generated by Django 3.1.12 on 2021-07-03 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0017_auto_20210702_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('currency', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 13, 38, 12, 648981)),
        ),
    ]
