# Generated by Django 3.1.12 on 2021-07-03 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0018_auto_20210703_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartpay',
            old_name='amount',
            new_name='cijena',
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 14, 2, 22, 500827)),
        ),
    ]
