# Generated by Django 3.1.12 on 2021-07-04 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0021_auto_20210703_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartpay',
            old_name='amount',
            new_name='cijena',
        ),
        migrations.RemoveField(
            model_name='cartpay',
            name='currency',
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 15, 48, 0, 825962)),
        ),
    ]
