# Generated by Django 3.1.12 on 2021-07-04 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0022_auto_20210704_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpay',
            name='cijena2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartpay',
            name='cijena3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 15, 54, 41, 852665)),
        ),
    ]
