# Generated by Django 3.1.12 on 2021-07-04 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0023_auto_20210704_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartpay',
            name='cijena3',
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 16, 0, 3, 49747)),
        ),
    ]
