# Generated by Django 3.1.12 on 2021-07-04 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0024_auto_20210704_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpay',
            name='cijena2',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 16, 3, 22, 277638)),
        ),
    ]
