# Generated by Django 3.1.12 on 2021-07-04 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0026_auto_20210704_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45, null=True)),
                ('number', models.IntegerField(null=True)),
                ('cijena', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CartPay',
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 16, 56, 24, 821819)),
        ),
    ]
