# Generated by Django 3.1.12 on 2021-07-05 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0027_auto_20210704_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 11, 21, 14, 783894)),
        ),
    ]
