# Generated by Django 3.1.12 on 2021-07-05 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0028_auto_20210705_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cijena',
        ),
        migrations.AddField(
            model_name='customer',
            name='id_customer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 11, 24, 37, 110090)),
        ),
    ]
