# Generated by Django 3.1.12 on 2021-07-05 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0030_auto_20210705_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cijena',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 11, 53, 4, 526599)),
        ),
    ]
