# Generated by Django 3.1.12 on 2021-07-05 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0031_auto_20210705_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='proizvodi',
            field=models.CharField(max_length=1145, null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 13, 2, 39, 61042)),
        ),
    ]
