# Generated by Django 3.1.12 on 2021-07-05 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0032_auto_20210705_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45, null=True)),
                ('number', models.CharField(max_length=100, null=True)),
                ('id_customer', models.CharField(max_length=100, null=True)),
                ('cijena', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 15, 11, 45, 151854)),
        ),
    ]
