# Generated by Django 3.1.12 on 2021-07-05 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0033_auto_20210705_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custome',
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 23, 41, 52, 882268)),
        ),
    ]
