# Generated by Django 3.1.12 on 2021-07-06 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0036_auto_20210706_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='iznos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 22, 33, 4, 667011)),
        ),
    ]
