# Generated by Django 3.1.12 on 2021-07-10 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0038_auto_20210710_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kmesages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=60)),
                ('kmessages', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='date_start_pay',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 17, 56, 6, 356370)),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 17, 56, 6, 355369)),
        ),
    ]
