# Generated by Django 3.1.12 on 2021-07-10 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0041_auto_20210710_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_start_pay',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 17, 58, 27, 948894)),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 17, 58, 27, 947894)),
        ),
    ]
