# Generated by Django 3.1.12 on 2021-07-10 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0043_auto_20210710_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_start_pay',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 18, 21, 32, 637121)),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='date_start',
            field=models.DateTimeField(default=datetime.date(2021, 7, 11)),
        ),
    ]
