# Generated by Django 3.1.12 on 2021-07-10 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0044_auto_20210710_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_start_pay',
            field=models.DateTimeField(default=datetime.date(2021, 7, 11)),
        ),
    ]
