# Generated by Django 3.1.12 on 2021-07-10 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0046_auto_20210710_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_start_pay',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 18, 46, 8, 22823)),
        ),
    ]
